require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IncisosController do

  # This should return the minimal set of attributes required to create a valid
  # Inciso. As you add validations to Inciso, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "codigo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IncisosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all incisos as @incisos" do
      inciso = Inciso.create! valid_attributes
      get :index, {}, valid_session
      assigns(:incisos).should eq([inciso])
    end
  end

  describe "GET show" do
    it "assigns the requested inciso as @inciso" do
      inciso = Inciso.create! valid_attributes
      get :show, {:id => inciso.to_param}, valid_session
      assigns(:inciso).should eq(inciso)
    end
  end

  describe "GET new" do
    it "assigns a new inciso as @inciso" do
      get :new, {}, valid_session
      assigns(:inciso).should be_a_new(Inciso)
    end
  end

  describe "GET edit" do
    it "assigns the requested inciso as @inciso" do
      inciso = Inciso.create! valid_attributes
      get :edit, {:id => inciso.to_param}, valid_session
      assigns(:inciso).should eq(inciso)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Inciso" do
        expect {
          post :create, {:inciso => valid_attributes}, valid_session
        }.to change(Inciso, :count).by(1)
      end

      it "assigns a newly created inciso as @inciso" do
        post :create, {:inciso => valid_attributes}, valid_session
        assigns(:inciso).should be_a(Inciso)
        assigns(:inciso).should be_persisted
      end

      it "redirects to the created inciso" do
        post :create, {:inciso => valid_attributes}, valid_session
        response.should redirect_to(Inciso.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved inciso as @inciso" do
        # Trigger the behavior that occurs when invalid params are submitted
        Inciso.any_instance.stub(:save).and_return(false)
        post :create, {:inciso => { "codigo" => "invalid value" }}, valid_session
        assigns(:inciso).should be_a_new(Inciso)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Inciso.any_instance.stub(:save).and_return(false)
        post :create, {:inciso => { "codigo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested inciso" do
        inciso = Inciso.create! valid_attributes
        # Assuming there are no other incisos in the database, this
        # specifies that the Inciso created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Inciso.any_instance.should_receive(:update).with({ "codigo" => "MyString" })
        put :update, {:id => inciso.to_param, :inciso => { "codigo" => "MyString" }}, valid_session
      end

      it "assigns the requested inciso as @inciso" do
        inciso = Inciso.create! valid_attributes
        put :update, {:id => inciso.to_param, :inciso => valid_attributes}, valid_session
        assigns(:inciso).should eq(inciso)
      end

      it "redirects to the inciso" do
        inciso = Inciso.create! valid_attributes
        put :update, {:id => inciso.to_param, :inciso => valid_attributes}, valid_session
        response.should redirect_to(inciso)
      end
    end

    describe "with invalid params" do
      it "assigns the inciso as @inciso" do
        inciso = Inciso.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Inciso.any_instance.stub(:save).and_return(false)
        put :update, {:id => inciso.to_param, :inciso => { "codigo" => "invalid value" }}, valid_session
        assigns(:inciso).should eq(inciso)
      end

      it "re-renders the 'edit' template" do
        inciso = Inciso.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Inciso.any_instance.stub(:save).and_return(false)
        put :update, {:id => inciso.to_param, :inciso => { "codigo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested inciso" do
      inciso = Inciso.create! valid_attributes
      expect {
        delete :destroy, {:id => inciso.to_param}, valid_session
      }.to change(Inciso, :count).by(-1)
    end

    it "redirects to the incisos list" do
      inciso = Inciso.create! valid_attributes
      delete :destroy, {:id => inciso.to_param}, valid_session
      response.should redirect_to(incisos_url)
    end
  end

end
