require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PartidaPrincipalsController do

  # This should return the minimal set of attributes required to create a valid
  # PartidaPrincipal. As you add validations to PartidaPrincipal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "codigo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PartidaPrincipalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all partidas_principales as @partidas_principales" do
      partida_principal = PartidaPrincipal.create! valid_attributes
      get :index, {}, valid_session
      assigns(:partidas_principales).should eq([partida_principal])
    end
  end

  describe "GET show" do
    it "assigns the requested partida_principal as @partida_principal" do
      partida_principal = PartidaPrincipal.create! valid_attributes
      get :show, {:id => partida_principal.to_param}, valid_session
      assigns(:partida_principal).should eq(partida_principal)
    end
  end

  describe "GET new" do
    it "assigns a new partida_principal as @partida_principal" do
      get :new, {}, valid_session
      assigns(:partida_principal).should be_a_new(PartidaPrincipal)
    end
  end

  describe "GET edit" do
    it "assigns the requested partida_principal as @partida_principal" do
      partida_principal = PartidaPrincipal.create! valid_attributes
      get :edit, {:id => partida_principal.to_param}, valid_session
      assigns(:partida_principal).should eq(partida_principal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PartidaPrincipal" do
        expect {
          post :create, {:partida_principal => valid_attributes}, valid_session
        }.to change(PartidaPrincipal, :count).by(1)
      end

      it "assigns a newly created partida_principal as @partida_principal" do
        post :create, {:partida_principal => valid_attributes}, valid_session
        assigns(:partida_principal).should be_a(PartidaPrincipal)
        assigns(:partida_principal).should be_persisted
      end

      it "redirects to the created partida_principal" do
        post :create, {:partida_principal => valid_attributes}, valid_session
        response.should redirect_to(PartidaPrincipal.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved partida_principal as @partida_principal" do
        # Trigger the behavior that occurs when invalid params are submitted
        PartidaPrincipal.any_instance.stub(:save).and_return(false)
        post :create, {:partida_principal => { "codigo" => "invalid value" }}, valid_session
        assigns(:partida_principal).should be_a_new(PartidaPrincipal)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PartidaPrincipal.any_instance.stub(:save).and_return(false)
        post :create, {:partida_principal => { "codigo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested partida_principal" do
        partida_principal = PartidaPrincipal.create! valid_attributes
        # Assuming there are no other partidas_principales in the database, this
        # specifies that the PartidaPrincipal created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PartidaPrincipal.any_instance.should_receive(:update).with({ "codigo" => "MyString" })
        put :update, {:id => partida_principal.to_param, :partida_principal => { "codigo" => "MyString" }}, valid_session
      end

      it "assigns the requested partida_principal as @partida_principal" do
        partida_principal = PartidaPrincipal.create! valid_attributes
        put :update, {:id => partida_principal.to_param, :partida_principal => valid_attributes}, valid_session
        assigns(:partida_principal).should eq(partida_principal)
      end

      it "redirects to the partida_principal" do
        partida_principal = PartidaPrincipal.create! valid_attributes
        put :update, {:id => partida_principal.to_param, :partida_principal => valid_attributes}, valid_session
        response.should redirect_to(partida_principal)
      end
    end

    describe "with invalid params" do
      it "assigns the partida_principal as @partida_principal" do
        partida_principal = PartidaPrincipal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PartidaPrincipal.any_instance.stub(:save).and_return(false)
        put :update, {:id => partida_principal.to_param, :partida_principal => { "codigo" => "invalid value" }}, valid_session
        assigns(:partida_principal).should eq(partida_principal)
      end

      it "re-renders the 'edit' template" do
        partida_principal = PartidaPrincipal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PartidaPrincipal.any_instance.stub(:save).and_return(false)
        put :update, {:id => partida_principal.to_param, :partida_principal => { "codigo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested partida_principal" do
      partida_principal = PartidaPrincipal.create! valid_attributes
      expect {
        delete :destroy, {:id => partida_principal.to_param}, valid_session
      }.to change(PartidaPrincipal, :count).by(-1)
    end

    it "redirects to the partidas_principales list" do
      partida_principal = PartidaPrincipal.create! valid_attributes
      delete :destroy, {:id => partida_principal.to_param}, valid_session
      response.should redirect_to(partidas_principales_url)
    end
  end

end
