require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecepcionesDeBienDeConsumoController do

  # This should return the minimal set of attributes required to create a valid
  # RecepcionDeBienDeConsumo. As you add validations to RecepcionDeBienDeConsumo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "fecha" => "2014-10-22 13:55:10" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecepcionesDeBienDeConsumoController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all recepciones_de_bien_de_consumo as @recepciones_de_bien_de_consumo" do
      recepcion_de_bien_de_consumo = RecepcionDeBienDeConsumo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recepciones_de_bien_de_consumo).should eq([recepcion_de_bien_de_consumo])
    end
  end

  describe "GET show" do
    it "assigns the requested recepcion_de_bien_de_consumo as @recepcion_de_bien_de_consumo" do
      recepcion_de_bien_de_consumo = RecepcionDeBienDeConsumo.create! valid_attributes
      get :show, {:id => recepcion_de_bien_de_consumo.to_param}, valid_session
      assigns(:recepcion_de_bien_de_consumo).should eq(recepcion_de_bien_de_consumo)
    end
  end

  describe "GET new" do
    it "assigns a new recepcion_de_bien_de_consumo as @recepcion_de_bien_de_consumo" do
      get :new, {}, valid_session
      assigns(:recepcion_de_bien_de_consumo).should be_a_new(RecepcionDeBienDeConsumo)
    end
  end

  describe "GET edit" do
    it "assigns the requested recepcion_de_bien_de_consumo as @recepcion_de_bien_de_consumo" do
      recepcion_de_bien_de_consumo = RecepcionDeBienDeConsumo.create! valid_attributes
      get :edit, {:id => recepcion_de_bien_de_consumo.to_param}, valid_session
      assigns(:recepcion_de_bien_de_consumo).should eq(recepcion_de_bien_de_consumo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RecepcionDeBienDeConsumo" do
        expect {
          post :create, {:recepcion_de_bien_de_consumo => valid_attributes}, valid_session
        }.to change(RecepcionDeBienDeConsumo, :count).by(1)
      end

      it "assigns a newly created recepcion_de_bien_de_consumo as @recepcion_de_bien_de_consumo" do
        post :create, {:recepcion_de_bien_de_consumo => valid_attributes}, valid_session
        assigns(:recepcion_de_bien_de_consumo).should be_a(RecepcionDeBienDeConsumo)
        assigns(:recepcion_de_bien_de_consumo).should be_persisted
      end

      it "redirects to the created recepcion_de_bien_de_consumo" do
        post :create, {:recepcion_de_bien_de_consumo => valid_attributes}, valid_session
        response.should redirect_to(RecepcionDeBienDeConsumo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recepcion_de_bien_de_consumo as @recepcion_de_bien_de_consumo" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecepcionDeBienDeConsumo.any_instance.stub(:save).and_return(false)
        post :create, {:recepcion_de_bien_de_consumo => { "fecha" => "invalid value" }}, valid_session
        assigns(:recepcion_de_bien_de_consumo).should be_a_new(RecepcionDeBienDeConsumo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecepcionDeBienDeConsumo.any_instance.stub(:save).and_return(false)
        post :create, {:recepcion_de_bien_de_consumo => { "fecha" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recepcion_de_bien_de_consumo" do
        recepcion_de_bien_de_consumo = RecepcionDeBienDeConsumo.create! valid_attributes
        # Assuming there are no other recepciones_de_bien_de_consumo in the database, this
        # specifies that the RecepcionDeBienDeConsumo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RecepcionDeBienDeConsumo.any_instance.should_receive(:update).with({ "fecha" => "2014-10-22 13:55:10" })
        put :update, {:id => recepcion_de_bien_de_consumo.to_param, :recepcion_de_bien_de_consumo => { "fecha" => "2014-10-22 13:55:10" }}, valid_session
      end

      it "assigns the requested recepcion_de_bien_de_consumo as @recepcion_de_bien_de_consumo" do
        recepcion_de_bien_de_consumo = RecepcionDeBienDeConsumo.create! valid_attributes
        put :update, {:id => recepcion_de_bien_de_consumo.to_param, :recepcion_de_bien_de_consumo => valid_attributes}, valid_session
        assigns(:recepcion_de_bien_de_consumo).should eq(recepcion_de_bien_de_consumo)
      end

      it "redirects to the recepcion_de_bien_de_consumo" do
        recepcion_de_bien_de_consumo = RecepcionDeBienDeConsumo.create! valid_attributes
        put :update, {:id => recepcion_de_bien_de_consumo.to_param, :recepcion_de_bien_de_consumo => valid_attributes}, valid_session
        response.should redirect_to(recepcion_de_bien_de_consumo)
      end
    end

    describe "with invalid params" do
      it "assigns the recepcion_de_bien_de_consumo as @recepcion_de_bien_de_consumo" do
        recepcion_de_bien_de_consumo = RecepcionDeBienDeConsumo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecepcionDeBienDeConsumo.any_instance.stub(:save).and_return(false)
        put :update, {:id => recepcion_de_bien_de_consumo.to_param, :recepcion_de_bien_de_consumo => { "fecha" => "invalid value" }}, valid_session
        assigns(:recepcion_de_bien_de_consumo).should eq(recepcion_de_bien_de_consumo)
      end

      it "re-renders the 'edit' template" do
        recepcion_de_bien_de_consumo = RecepcionDeBienDeConsumo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecepcionDeBienDeConsumo.any_instance.stub(:save).and_return(false)
        put :update, {:id => recepcion_de_bien_de_consumo.to_param, :recepcion_de_bien_de_consumo => { "fecha" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recepcion_de_bien_de_consumo" do
      recepcion_de_bien_de_consumo = RecepcionDeBienDeConsumo.create! valid_attributes
      expect {
        delete :destroy, {:id => recepcion_de_bien_de_consumo.to_param}, valid_session
      }.to change(RecepcionDeBienDeConsumo, :count).by(-1)
    end

    it "redirects to the recepciones_de_bien_de_consumo list" do
      recepcion_de_bien_de_consumo = RecepcionDeBienDeConsumo.create! valid_attributes
      delete :destroy, {:id => recepcion_de_bien_de_consumo.to_param}, valid_session
      response.should redirect_to(recepciones_de_bien_de_consumo_url)
    end
  end

end
